FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update

RUN apt install -y bash coreutils git git-lfs curl wget gnupg ca-certificates tar gzip unzip sudo

RUN apt upgrade -y

RUN apt clean && rm -rf /var/lib/apt/lists/*

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENTRYPOINT []
CMD []
USER root
