#!/bin/bash
#  Open file audio in external tool
#  Copyright (C) 2021 scrubbbbs
#  Contact: screubbbebs@gemeaile.com =~ s/e//g
#  Project: https://github.com/scrubbbbs/cbird

#  This file is part of cbird.

#  cbird is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public
#  License as published by the Free Software Foundation; either
#  version 2 of the License, or (at your option) any later version.
#
#  cbird is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public
#  License along with cbird; if not, see
#  <https://www.gnu.org/licenses/>.
#
# ff-compare-audio
#
# Extract audio with ffmpeg to /tmp and
# open in audio editor for manual
# inspection
#

files=()

if [ -z $TMPDIR ]; then
  TMPDIR=/tmp
fi

for x in "$@"; do 
  out=$(basename "$x")
  out="${TMPDIR}/$out.wav"
  echo $out
  ffmpeg -i "$x" "$out" &
  files+=("$out")
done

wait $(jobs -p)
ocenaudio "${files[@]}"
#/opt/Ardour-6.6.0/bin/ardour6 "${files[@]}"

rm -fv "${files[@]}"

